# Schema for the configuration files of the Open Accessibility.

open_accessibility.settings:
  type: config_object
  label: 'Open Accessibility'
  mapping:
    menu_opened:
      type: boolean
      label: 'Menu is opened'
    mobile_enabled:
      type: boolean
      label: 'Enable in the mobile'
    text_selector:
      type: string
      label: 'Text selector for Zoom'
    icon_size:
      type: string
      label: 'Icon size for the Options'
